/**
 * START-TEMPLATE RESOLUTION — turns a request into the runnable file set the
 * agentic edit loop starts from, across the WHOLE stack matrix:
 *
 *   curated  → the inline hand-authored template (registry.ts)
 *   seed     → the minimal runnable seed for the stack (seeds.ts)
 *   scaffold → run the stack's OFFICIAL generator in the sandbox (scaffolder.ts);
 *              if no sandbox is available, fall back to a seed/curated starter.
 *
 * Always returns a Template (never throws), so every request — React to Rust to
 * Prolog — begins from something that builds.
 */
import { TEMPLATES, selectTemplate, type Template } from "./registry";
import { selectScaffoldOrSeed, type StackEntry } from "./matrix";
import { getSeed } from "./seeds";
import { runScaffolder } from "./scaffolder";
import { isSandboxConfigured, vercelSandboxFactory } from "@/lib/deploy/vercel-sandbox-runner";
import type { SandboxFactory } from "@/lib/deploy/sandbox-verify";

export interface ResolvedStart {
  template: Template;
  strategy: "curated" | "seed" | "scaffold" | "scaffold-fallback";
}

export interface ResolveOpts {
  /** Inject a sandbox factory (tests / explicit control). Defaults to the real one when configured. */
  factory?: SandboxFactory | null;
}

/** The starter to use when a scaffold can't run (no sandbox). */
function fallbackStarter(entry: StackEntry): Template {
  if (entry.stack === "node") return TEMPLATES["react-vite"]; // closest runnable node starter
  return getSeed(entry.stack, entry.framework);
}

/** Build a Template wrapper around a scaffolded file set. */
function scaffoldedTemplate(entry: StackEntry, files: Record<string, string>): Template {
  return {
    key: (entry.curatedKey ?? "static") as Template["key"],
    label: entry.label,
    stack: entry.stack,
    framework: entry.framework,
    description: `${entry.label} — generated by its official scaffolder (${entry.scaffold?.tool}). Build the requested app on top.`,
    runtime: { install: "", build: null, dev: "", port: 0 },
    files,
  };
}

export async function resolveStartTemplate(request: string, opts: ResolveOpts = {}): Promise<ResolvedStart> {
  const entry = selectScaffoldOrSeed(request);
  // No specific non-curated stack named → use the curated picker (React/Vue/etc.).
  if (!entry) return { template: selectTemplate(request), strategy: "curated" };

  if (entry.strategy === "seed") {
    return { template: getSeed(entry.stack, entry.framework), strategy: "seed" };
  }

  // scaffold tier — run the official generator if a sandbox is available.
  const factory = opts.factory === undefined ? (isSandboxConfigured() ? vercelSandboxFactory : null) : opts.factory;
  if (entry.scaffold && factory) {
    try {
      const files = await runScaffolder(entry.scaffold, { factory });
      if (files.length) {
        const map: Record<string, string> = {};
        for (const f of files) map[f.path] = f.content;
        return { template: scaffoldedTemplate(entry, map), strategy: "scaffold" };
      }
    } catch {
      /* fall through to fallback */
    }
  }
  // No sandbox (or the generator produced nothing) → a runnable fallback starter.
  return { template: fallbackStarter(entry), strategy: "scaffold-fallback" };
}
